#!/usr/bin/env python3
"""Emit experiments/G1/k8s/job-g1-<arm>-lr<tag>-raunav.yaml -- the LR sweep.

WHAT G1 IS FOR
--------------
`docs/GATES.md`: 2 arms x 3 learning rates at 20% budget. L162 and R16_Q1 are
the ladder's ENDPOINTS, so if the optimum does not move between them it will not
move in between.

  Pass:   the LR optimum is the same for both arms -> one LR is defensible.
  Kill:   the optimum MOVES with K -> a single LR confounds granularity with
          tuning, every arm needs its own sweep, and that is a YELLOW
          escalation, not a silent fix.

Without this, all three full-budget arms run at a hardcoded 5e-4 and a later
finding that the optimum moves invalidates ~24 GPU-days retroactively.

DERIVED FROM THE SEED-1 MTX JOBS, NOT FROM build_arm_jobs.py
------------------------------------------------------------
`scripts/build_arm_jobs.py` is stale (see its header). The committed MTX seed-1
YAMLs carry five launch-blocking fixes it does not, so this script derives from
those YAMLs by targeted substitution. Everything not listed in EDITS below is
copied byte-for-byte, which is what keeps G1 comparable to the runs it informs.

THE GRID
--------
Log-spaced, factor of 2, bracketing the incumbent 5e-4:

    2.5e-4   5e-4 (incumbent)   1e-3 (what E1 trained at, successfully)

Factor-of-2 spacing is tight enough that every point trains and wide enough to
resolve a shift of one grid step between the endpoints -- which is the only
thing the gate asks.

BUDGET
------
20% of the full run: 16 epochs instead of 80, at the same 10,240,000
samples/epoch. samples-per-epoch is deliberately NOT reduced -- shrinking the
epoch would change the LR schedule's shape (weaver's flat+decay is defined over
epochs), and then the sweep would not be measuring the thing it will be applied
to.

Run:  python3 scripts/build_g1_jobs.py
"""
from __future__ import annotations

import pathlib
import re
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = {
    "L162": ROOT / "experiments/MTX/k8s/job-mtx-l162-s1-raunav.yaml",
    "R16_Q1": ROOT / "experiments/MTX/k8s/job-mtx-r16_q1-s1-raunav.yaml",
}
OUT_DIR = ROOT / "experiments/G1/k8s"

# lr value -> filename/RUN_ID tag. Tags avoid '.' and '-' in the numeric part so
# the resulting Job names stay RFC 1123 (the underscore bug that bit MTX).
RATES = [("2.5e-4", "25e5"), ("5e-4", "5e4"), ("1e-3", "1e3")]
EPOCHS = 16          # 20% of 80
FULL_EPOCHS = 80


def build(arm: str, lr: str, tag: str) -> tuple[str, str]:
    text = SRC[arm].read_text()
    arm_lc = arm.lower().replace("_", "")
    old_name = f"mtx-{arm_lc}-s1"
    new_name = f"g1-{arm_lc}-lr{tag}"

    # 1. identity: job name, RUN_ID, output dir, tensorboard tag
    text = text.replace(f"name: {old_name}-raunav", f"name: {new_name}-raunav")
    text = text.replace(f"RUN_ID={old_name}", f"RUN_ID={new_name}")
    text = text.replace("/data/results/mtx/${RUN_ID}", "/data/results/g1/${RUN_ID}")
    text = re.sub(r"--tensorboard \S+", f"--tensorboard {new_name}", text)

    # 2. the swept variable
    n_lr = text.count("--start-lr 5e-4")
    if n_lr != 1:
        sys.exit(f"FATAL: {arm}: expected 1 --start-lr, found {n_lr}")
    text = text.replace("--start-lr 5e-4", f"--start-lr {lr}")

    # 3. budget: 80 -> 16 epochs, in BOTH the weaver arg and the manifest arg
    n_ep = text.count(f"--num-epochs {FULL_EPOCHS}")
    if n_ep != 2:
        sys.exit(f"FATAL: {arm}: expected 2 --num-epochs, found {n_ep}")
    text = text.replace(f"--num-epochs {FULL_EPOCHS}", f"--num-epochs {EPOCHS}")

    # 4. header, so the file does not describe itself as the full-budget run
    text = text.replace(
        "  # CORE-MATRIX GRANULARITY ARM --",
        f"  # G1 LEARNING-RATE SWEEP POINT: lr={lr}, {EPOCHS} epochs (20% budget).\n"
        f"  # Generated by scripts/build_g1_jobs.py from the seed-1 MTX job.\n"
        f"  # Differs from it ONLY in: name/RUN_ID/output dir/tensorboard tag,\n"
        f"  # --start-lr, and --num-epochs. Everything else is byte-identical.\n"
        f"  #\n"
        f"  # ORIGINALLY --")
    return f"job-{new_name}-raunav.yaml", text


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    written = []
    for arm in SRC:
        if not SRC[arm].exists():
            sys.exit(f"FATAL: {SRC[arm]} not found")
        for lr, tag in RATES:
            fname, text = build(arm, lr, tag)
            d = yaml.safe_load(text)                     # must parse
            name = d["metadata"]["name"]
            if not re.fullmatch(r"[a-z0-9]([-a-z0-9.]*[a-z0-9])?", name):
                sys.exit(f"FATAL: {name} is not a valid RFC 1123 name")
            args = d["spec"]["template"]["spec"]["containers"][0]["args"][0]
            assert f"--start-lr {lr}" in args, fname
            assert f"--num-epochs {EPOCHS}" in args, fname
            assert "--data-test" not in args, fname
            (OUT_DIR / fname).write_text(text)
            written.append((name, arm, lr))
    print(f"wrote {len(written)} job specs to {OUT_DIR.relative_to(ROOT)}/")
    for name, arm, lr in written:
        print(f"  {name:28s} arm={arm:7s} lr={lr}  epochs={EPOCHS}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
