#!/usr/bin/env python3
"""Emit the two mass-auxiliary training specs and bring R42_Q1's spec to launch
state.

DERIVED, NOT WRITTEN
--------------------
experiments/MTX/k8s/job-mtx-r16_q1-s1-raunav.yaml is the launch-ready template
(auto-resume + recipe guard, --lean-val-metrics, 3090 pin, split guard,
sidecar guard). A mass spec is that file with EXACTLY these edit sites changed:

    header                       what the arm is and why its rate is its twin's
    metadata.name, RUN_ID        mtx-<slug>mass-s1
    REPO_REF                     the pin every job in this wave clones
    the config path              configs/arms/<ARM>_MASS.yaml  (CFG, SIDECAR,
                                 SRC, --data-config x2)
    the sidecar guard            a BOUNDED WAIT instead of a hard exit: the
                                 makeweight-mass CPU job runs alongside and
                                 finishes in hours, a GPU frees in days, and
                                 with backoffLimit 50 a hard exit would burn
                                 every retry in minutes
    manifest                     --arm <ARM>_MASS, --num-classes K, --lambda-mass
    weaver call                  --mass-lambda, the mass arch, -o num_classes K,
                                 --start-lr (its twin's), --tensorboard
    RECIPE                       carries lambda, so a resume across a lambda
                                 change is refused like a rate change

Everything else is byte-identical. That is invariant I1 at the launch layer
for the mass axis: a mass arm and its twin differ in one output node, the loss
term that trains it, and nothing else. `-o num_classes K` is the twin's K; the
arch adds the node (experiments/MTX/ParT_sophon_arch_mass.py).

lambda = 5.0 = GloParT v3beta4's gamma. docs/RUN_MATRIX.md: when compute
binds, cut the lambda fork to one value. It binds (DECISIONS_PENDING item 9).

R42_Q1
------
The committed spec predates auto-resume and --lean-val-metrics and pins
mtx-s1.1. patch_r42() applies the deltas scripts/build_mtx_launch.patch()
applies, minus the rate: 2.5e-4 is already declared and written.

Run:  python3 scripts/build_mass_jobs.py [--pin TAG] [--check-only]
"""
from __future__ import annotations

import argparse
import importlib.util
import pathlib
import re
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
K8S = ROOT / "experiments" / "MTX" / "k8s"
TEMPLATE = K8S / "job-mtx-r16_q1-s1-raunav.yaml"
R42 = K8S / "job-mtx-r42_q1-s1-raunav.yaml"
PIN = "mtx-s1.8"
LAMBDA = "5.0"

# arm -> (K, rate). The rate is the twin's, from build_mtx_launch.RATES.
MASS_ARMS = {"L162": 162, "R16_Q1": 17}


def _rates():
    spec = importlib.util.spec_from_file_location(
        "build_mtx_launch", ROOT / "scripts" / "build_mtx_launch.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.RATES


def _autoresume():
    spec = importlib.util.spec_from_file_location(
        "add_autoresume", ROOT / "scripts" / "add_autoresume.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _sub(text: str, old: str, new: str, n: int = 1) -> str:
    got = text.count(old)
    if got != n:
        raise SystemExit(f"FAILED: expected {n} x {old!r}, found {got}")
    return text.replace(old, new)


def mass_spec(template: str, arm: str, k: int, rate: str, pin: str, why: str) -> str:
    slug = arm.lower().replace("_", "") + "mass"       # mtx-r16q1mass-s1
    t = template

    # header
    t = _sub(t, "  # CORE-MATRIX GRANULARITY ARM -- R16_Q1 (K = 17), seed 1\n",
             f"  # MASS-AUXILIARY ARM -- {arm}_MASS (K = {k} classes + 1 mass node), seed 1\n"
             f"  #\n"
             f"  # The 2x2 {{L162, R16_Q1}} x {{+/- mass}} (DECISIONS_PENDING item 14,\n"
             f"  # addendum 2). This arm is {arm} plus ONE output node trained on\n"
             f"  # log(genjet_sdmass / jet_sdmass) with GloParT's log-cosh loss at\n"
             f"  # lambda = {LAMBDA} (experiments/MTX/hybrid_mass.py). Same trunk, same\n"
             f"  # stream (I2), same rate as its twin: {why}\n")
    t = _sub(t, "  # GENERATED by scripts/build_arm_jobs.py -- do not hand-edit. Regenerate.\n",
             "  # GENERATED by scripts/build_mass_jobs.py from job-mtx-r16_q1-s1-raunav.yaml\n"
             "  # -- do not hand-edit. Regenerate.\n")
    t = _sub(t, "  name: mtx-r16q1-s1-raunav\n", f"  name: mtx-{slug}-s1-raunav\n")
    t = re.sub(r'value: "mtx-s1[^"]*"', f'value: "{pin}"', t, count=1)
    t = _sub(t, "RUN_ID=mtx-r16q1-s1\n", f"RUN_ID=mtx-{slug}-s1\n")

    # config, sidecar, and the guard -> bounded wait
    t = _sub(t, "CFG=configs/arms/R16_Q1.yaml\n", f"CFG=configs/arms/{arm}_MASS.yaml\n")
    t = _sub(t, "SIDECAR=configs/arms/R16_Q1.${MD5}.auto.yaml\n",
             f"SIDECAR=configs/arms/{arm}_MASS.${{MD5}}.auto.yaml\n")
    t = _sub(t, "SRC=/data/results/mtx/makeweight/R16_Q1.${MD5}.auto.yaml\n",
             f"SRC=/data/results/mtx/makeweight/{arm}_MASS.${{MD5}}.auto.yaml\n")
    guard = ('          [ -f "${SRC}" ] || { echo "FATAL: no reweighting sidecar at ${SRC}. '
             'Run job-mtx-makeweight-raunav first. If it HAS run, then '
             'configs/arms/R16_Q1.yaml changed afterwards (its md5 is in the filename) '
             'and make_weight must be re-run."; exit 1; }\n')
    wait = (
        "          # The sidecar comes from job-mtx-makeweight-mass-raunav (CPU), applied\n"
        "          # BEFORE this job; it finishes in hours, a GPU frees in days. So this\n"
        "          # wait is a guard, bounded at 2 h, and it leaves a marker: with\n"
        "          # backoffLimit 50 a bare exit 1 would re-queue and hold a GPU for\n"
        "          # another 2 h per retry; the marker makes every retry fail at once.\n"
        '          mkdir -p "${OUT}"\n'
        "          WAIT_MARK=${OUT}/WAIT_TIMEOUT\n"
        '          [ -f "${WAIT_MARK}" ] && { echo "FATAL: an earlier attempt timed out: $(cat ${WAIT_MARK}). Fix job-mtx-makeweight-mass-raunav, then remove ${WAIT_MARK}"; exit 1; }\n'
        "          WAITED=0\n"
        '          until [ -f "${SRC}" ]; do\n'
        '            [ "${WAITED}" -ge 7200 ] && { echo "no reweighting sidecar at ${SRC} after 2 h. '
        'Run job-mtx-makeweight-mass-raunav. If it HAS run, then '
        f'configs/arms/{arm}_MASS.yaml changed afterwards (its md5 is in the filename) '
        'and make_weight must be re-run." | tee "${WAIT_MARK}"; exit 1; }\n'
        "            sleep 60; WAITED=$((WAITED+60))\n"
        "          done\n")
    t = _sub(t, guard, wait)

    # manifest
    t = _sub(t, "            --arm R16_Q1 \\\n", f"            --arm {arm}_MASS \\\n")
    t = _sub(t, "            --num-classes 17 \\\n", f"            --num-classes {k} \\\n")
    t = _sub(t, "            --data-config configs/arms/R16_Q1.yaml \\\n",
             f"            --data-config configs/arms/{arm}_MASS.yaml \\\n", n=2)
    t = _sub(t, "            --batch-size 512 \\\n            --out ${OUT}/run_manifest.json\n",
             f"            --batch-size 512 \\\n            --lambda-mass {LAMBDA} \\\n"
             "            --out ${OUT}/run_manifest.json\n")

    # recipe + weaver call
    t = _sub(t, "RECIPE='lr=5e-4 epochs=80'\n", f"RECIPE='lr={rate} epochs=80 lambda={LAMBDA}'\n")
    t = _sub(t, "            --lean-val-metrics \\\n",
             f"            --lean-val-metrics --mass-lambda {LAMBDA} \\\n")
    t = _sub(t, "            --network-config experiments/MTX/ParT_sophon_arch_mtx.py \\\n",
             "            --network-config experiments/MTX/ParT_sophon_arch_mass.py \\\n")
    t = _sub(t, "            -o num_classes 17 -o fc_params '[(512,0.1)]' \\\n",
             f"            -o num_classes {k} -o fc_params '[(512,0.1)]' \\\n")
    t = _sub(t, "--use-amp --batch-size 512 --start-lr 5e-4 \\\n",
             f"--use-amp --batch-size 512 --start-lr {rate} \\\n")
    t = _sub(t, "            --tensorboard mtx_R16_Q1_s1\n", f"            --tensorboard mtx_{arm}_MASS_s1\n")

    # nothing of the template arm may survive outside the comments
    d = yaml.safe_load(t)
    args = d["spec"]["template"]["spec"]["containers"][0]["args"][0]
    code = "\n".join(ln for ln in args.splitlines() if not ln.lstrip().startswith("#"))
    for must in (f"configs/arms/{arm}_MASS.yaml", f"-o num_classes {k}", f"--start-lr {rate}",
                 f"--mass-lambda {LAMBDA}", f"--lambda-mass {LAMBDA}", "ParT_sophon_arch_mass.py",
                 "${RESUME}", f"RECIPE='lr={rate} epochs=80 lambda={LAMBDA}'",
                 f"--arm {arm}_MASS", "until [ -f \"${SRC}\" ]", "--lean-val-metrics",
                 "WAIT_MARK", "-ge 7200"):
        if must not in code:
            raise SystemExit(f"FAILED ({arm}_MASS): emitted spec does not execute {must!r}")
    if re.search(r"configs/arms/R16_Q1\.yaml|R16_Q1\.\$\{MD5\}|--arm R16_Q1 |mtx_R16_Q1_s1", code):
        raise SystemExit(f"FAILED ({arm}_MASS): template arm survived in the executed code")
    if len(set(re.findall(r"--start-lr (\S+)", code))) != 1:
        raise SystemExit(f"FAILED ({arm}_MASS): --start-lr is not exactly one rate")
    if d["metadata"]["name"] != f"mtx-{slug}-s1-raunav" or d["spec"]["backoffLimit"] != 50:
        raise SystemExit(f"FAILED ({arm}_MASS): name or backoffLimit wrong")
    if f'value: "{pin}"' not in t or "NVIDIA-GeForce-RTX-3090" not in t:
        raise SystemExit(f"FAILED ({arm}_MASS): pin missing")
    return t


def patch_r42(pin: str, check_only: bool) -> str:
    text = R42.read_text()
    if "AUTO-RESUME" in text and f'value: "{pin}"' in text:
        return "already launch-ready"
    text = re.sub(r'value: "mtx-s1[^"]*"', f'value: "{pin}"', text, count=1)
    call = "python3 experiments/E1/seed_weaver.py \\"
    if "--lean-val-metrics" not in text:
        text = _sub(text, call, call + "\n            --lean-val-metrics \\")
    text = _sub(text, "  # CORE-MATRIX GRANULARITY ARM -- R42_Q1 (K = 43), seed 1\n",
                "  # CORE-MATRIX GRANULARITY ARM -- R42_Q1 (K = 43), seed 1\n"
                "  #\n"
                f"  # RELAUNCH WAVE 2026-09-05 (scripts/build_mass_jobs.py): pin -> {pin},\n"
                "  # --lean-val-metrics and auto-resume added, exactly the deltas\n"
                "  # scripts/build_mtx_launch.py applied to the other arms. Rate UNCHANGED\n"
                "  # at 2.5e-4, the declared RATES value (see RATE CORRECTED below).\n")
    tmp = R42.with_suffix(".yaml.tmp")
    try:
        tmp.write_text(text)
        r = _autoresume().patch(tmp)
        if r.startswith("FAILED"):
            raise SystemExit(f"FAILED (R42_Q1 autoresume): {r}")
        d = yaml.safe_load(tmp.read_text())
        code = "\n".join(ln for ln in d["spec"]["template"]["spec"]["containers"][0]["args"][0].splitlines()
                         if not ln.lstrip().startswith("#"))
        for must in ("--start-lr 2.5e-4", "${RESUME}", "--lean-val-metrics",
                     "RECIPE='lr=2.5e-4 epochs=80'", "configs/arms/R42_Q1.yaml", "-o num_classes 43"):
            if must not in code:
                raise SystemExit(f"FAILED (R42_Q1): emitted spec does not execute {must!r}")
        if d["spec"]["backoffLimit"] != 50 or f'value: "{pin}"' not in tmp.read_text():
            raise SystemExit("FAILED (R42_Q1): backoffLimit or pin")
        if not check_only:
            tmp.replace(R42)
        return f"launch-ready (lr=2.5e-4, pin {pin}, backoffLimit 50, auto-resume)"
    finally:
        if tmp.exists():
            tmp.unlink()


MAKEWEIGHT = K8S / "job-mtx-makeweight-raunav.yaml"
MAKEWEIGHT_MASS = K8S / "job-mtx-makeweight-mass-raunav.yaml"


def makeweight_mass_spec(pin: str) -> str:
    """The shared reweighting pass, for the two mass configs.

    Derived from job-mtx-makeweight-raunav.yaml (same 1675-file train+val
    list, same guards). Their md5s differ from their twins' (the labels block
    changed), so weaver names new sidecars; the histograms cannot differ
    (WeightMaker keeps reweight_branches + reweight_classes only), and the
    final step ASSERTS the realised histograms hash-equal the granularity arms'
    recorded value -- I2 measured across the mass axis.
    """
    t = MAKEWEIGHT.read_text()
    t = _sub(t, "  name: mtx-makeweight-raunav\n", "  name: mtx-makeweight-mass-raunav\n")
    t = _sub(t, "  # ONE SHARED REWEIGHTING PASS -- run BEFORE any training arm.\n",
             "  # GENERATED by scripts/build_mass_jobs.py from job-mtx-makeweight-raunav.yaml.\n"
             "  # THE SAME PASS FOR THE TWO MASS TWINS (DECISIONS_PENDING item 14). Their\n"
             "  # labels blocks carry two extra labels, so their md5s -- and sidecar names --\n"
             "  # differ from their twins'; the histograms must not, and the last step\n"
             "  # asserts that against hist_hashes.json from the original pass.\n"
             "  #\n"
             "  # ONE SHARED REWEIGHTING PASS -- run BEFORE any training arm.\n")
    t = _sub(t, "          git clone --depth 1 --branch arms-s1 \\\n",
             f'          git clone --depth 1 --branch {pin} \\\n')
    t = _sub(t, "          run_arm L162   162\n          run_arm R42_Q1  43\n          run_arm R16_Q1  17\n",
             "          run_arm L162_MASS    162\n          run_arm R16_Q1_MASS  17\n")
    t = _sub(t, '          arms = ["L162", "R42_Q1", "R16_Q1"]\n',
             '          arms = ["L162_MASS", "R16_Q1_MASS"]\n')
    t = _sub(t, 'IDENTICAL across all 3 arms', 'IDENTICAL across the mass twins')
    # the twins gate on the sidecar's existence under its final name, so nothing
    # may appear under that name until the measurement below has PASSED
    t = _sub(t, "          # Sequential, same pod. Each sidecar is copied out IMMEDIATELY after\n",
             "          # Sequential, same pod. Each sidecar is copied out (as .pending) IMMEDIATELY after\n")
    t = _sub(t, '            cp -v "${SIDECAR}" ${OUT}/\n',
             '            cp -v "${SIDECAR}" "${OUT}/$(basename ${SIDECAR}).pending"\n')
    t = _sub(t, "          PY\n\n          ls -la ${OUT}\n",
             "          PY\n\n"
             "          # Only a PASSING measurement releases the sidecars under the names the\n"
             "          # twins wait for: set -e stops here if the assertions above failed.\n"
             '          for p in ${OUT}/*_MASS.*.auto.yaml.pending; do mv -v "${p}" "${p%.pending}"; done\n'
             "          ls -la ${OUT}\n")
    t = _sub(t, '          json.dump(hh, open("/data/results/mtx/makeweight/hist_hashes.json", "w"), indent=2)\n',
             '          ref = json.load(open("/data/results/mtx/makeweight/hist_hashes.json"))\n'
             '          if hh and set(hh.values()) == {ref["L162"]}:\n'
             '              print(f"  [PASS] mass-twin reweight_hists IDENTICAL to the granularity arms\' ({ref[\'L162\'][:16]})")\n'
             '          else:\n'
             '              print(f"  [FAIL] mass-twin reweight_hists differ from the granularity arms\': {hh} vs {ref}")\n'
             '              failed += 1\n'
             '          json.dump(hh, open("/data/results/mtx/makeweight/hist_hashes_mass.json", "w"), indent=2)\n')
    d = yaml.safe_load(t)
    args = d["spec"]["template"]["spec"]["containers"][0]["args"][0]
    for must in ("run_arm L162_MASS    162", "run_arm R16_Q1_MASS  17", "hist_hashes_mass.json",
                 'ref["L162"]', f"--branch {pin}", "-eq 1675", "set -euo pipefail", ".pending"):
        if must not in args:
            raise SystemExit(f"FAILED (makeweight-mass): {must!r} missing")
    if not args.index("hist_hashes_mass.json") < args.index('mv -v "${p}" "${p%.pending}"'):
        raise SystemExit("FAILED (makeweight-mass): sidecars released before the measurement")
    if "nvidia.com/gpu" in t or d["metadata"]["name"] != "mtx-makeweight-mass-raunav":
        raise SystemExit("FAILED (makeweight-mass): GPU request or name")
    return t


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--pin", default=PIN)
    ap.add_argument("--check-only", action="store_true")
    args = ap.parse_args()
    rates = _rates()
    mw = makeweight_mass_spec(args.pin)
    if not args.check_only:
        MAKEWEIGHT_MASS.write_text(mw)
    print(f"{MAKEWEIGHT_MASS.name:40s} {'checked' if args.check_only else 'written'} (pin {args.pin})")
    template = TEMPLATE.read_text()
    for arm, k in MASS_ARMS.items():
        key = f"{arm}_MASS"
        if key not in rates:
            raise SystemExit(f"FAILED: build_mtx_launch.RATES has no entry for {key}")
        k_declared, rate, _br, why = rates[key]
        if k_declared != k or rates[arm][1] != rate:
            raise SystemExit(f"FAILED: {key} must declare K={k} and its twin's rate {rates[arm][1]}")
        text = mass_spec(template, arm, k, rate, args.pin, why)
        dst = K8S / f"job-mtx-{arm.lower()}_mass-s1-raunav.yaml"
        if not args.check_only:
            dst.write_text(text)
        print(f"{dst.name:40s} {'checked' if args.check_only else 'written'} (K={k}, lr={rate}, pin {args.pin})")
    print(f"{R42.name:40s} {patch_r42(args.pin, args.check_only)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
