#!/usr/bin/env python3
"""Emit experiments/MTX/k8s/job-mtx-<arm>-s<seed>-raunav.yaml -- one per run.

Generated rather than hand-written for the same reason the arm configs are:
every line that is not the arm name or the label map must be IDENTICAL across
arms, and three hand-edited copies of a 90-line spec drift. Invariant I1 is a
claim about the whole run, not just the data config -- if one arm gets a
different batch size or a different GPU model, the contrast is confounded and
nothing in the output records it.

WHAT DIFFERS PER JOB, and nothing else:
    metadata.name          mtx-<arm>-s<seed>-raunav
    --data-config          configs/arms/<ARM>.yaml
    -o num_classes         K for that arm
    --seed                 the master seed
    output paths

Run:  python3 scripts/build_arm_jobs.py [--check-only]
"""
from __future__ import annotations

import argparse
import csv
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
MAPS = ROOT / "configs" / "labelmaps" / "rung_label_maps.v1.csv"
OUT_DIR = ROOT / "experiments" / "MTX" / "k8s"

ARMS = ["L162", "R42_Q1", "R16_Q1"]
SEEDS = [1]

# ---------------------------------------------------------------- budget ---
# docs/GROUND_TRUTH.md: 8.192e8 examples seen, ~6.1 effective passes over the
# 110,087,593 selected training jets. NOT 8.4e8.
#   10,240,000 samples/epoch x 80 epochs = 819,200,000 = 8.192e8  exactly.
# The per-epoch figure is E1's, which is known to work end to end; only the
# epoch count changes. Asserted below rather than trusted.
SAMPLES_PER_EPOCH = 10_240_000
NUM_EPOCHS = 80
SAMPLES_PER_EPOCH_VAL = 1_280_000
TARGET_EXAMPLES = 819_200_000

BATCH_SIZE = 512
# 5e-4 is the FROZEN upstream Sophon JetClass-II rate
# (archive/v51_retired/experiments/E2/train_e2.sh: batchopts).
# An earlier version of this file carried 1e-3, which was E1's rate on
# JetClass-1 -- a different dataset. Carrying a hyperparameter across datasets
# because it happened to be in the last job spec is exactly the kind of silent
# deviation docs/GATES.md's G1 exists to prevent.
START_LR = "5e-4"

# Loading-only knobs, identical across arms, so I1/I2 are unaffected.
# weaver 0.4.17's DEFAULT event-fraction loader retains ~all loaded jets: it
# OOM-killed at ~5% of one epoch at BOTH 64Gi and 80Gi, independent of worker
# count and fetch-step size. fetch-by-files restores chunked streaming.
# Measured bounded band with these flags: 35-58 GB.
DATA_OPTS = "--num-workers 2 --fetch-by-files --fetch-step 5"

# ------------------------------------------------------- the 4:1:1 file split ---
# All three splits live in ONE directory, so a bare '*.parquet' glob trains on
# the val AND test files. Index ranges are upstream's
# (archive/v51_retired/experiments/E2/train_e2.sh).
#   train 1340 = 200 + 860 + 280
#   val    335 =  50 + 215 +  70
#   test   335 =  50 + 215 +  70
# The class-name prefix (Res2P:/Res34P:/QCD:) is how weaver groups files for
# reweighting; upstream applies it to train and test, not to val.
SPLITS = {
    "train": {"Res2P": (0, 199), "Res34P": (0, 859), "QCD": (0, 279)},
    "val":   {"Res2P": (200, 249), "Res34P": (860, 1074), "QCD": (280, 349)},
    "test":  {"Res2P": (250, 299), "Res34P": (1075, 1289), "QCD": (350, 419)},
}
EXPECTED_N = {"train": 1340, "val": 335, "test": 335}
DATA_DIR = "/jc2/jet_data"

# I7b: both arms of a seed pair must land on the SAME GPU model, or the pairing
# gain the seed budget assumes is silently lost. One product string, no
# allow-list, so a pair cannot straddle two models.
GPU_PRODUCT = "NVIDIA-A100-SXM4-80GB"

IMAGE = "gitlab-registry.nrp-nautilus.io/escheuller/transfer-learning:cu121"

# Every arm clones this ref. A BRANCH NAME IS NOT A PIN: three arms launched
# minutes or days apart would each get whatever the tip was at that moment.
# Override with --pin <tag-or-sha> once the launch commit exists; the default
# is deliberately the branch so an un-pinned launch is obvious in the diff.
REPO_REF = "main"

TEMPLATE = """apiVersion: batch/v1
kind: Job
metadata:
  # CORE-MATRIX GRANULARITY ARM -- {arm} (K = {k}), seed {seed}
  #
  # GENERATED by scripts/build_arm_jobs.py -- do not hand-edit. Regenerate.
  #
  # This job differs from its sibling arms at EXACTLY these edit sites, and no
  # others: this header, metadata.name, RUN_ID, --arm/--num-classes,
  # --data-config (x2), -o num_classes, and --tensorboard. All of them carry the
  # arm name or its K. Everything else -- resources, affinity, env, volumes,
  # backoffLimit, the file lists, the guards -- is byte-identical, which is
  # invariant I1 at the run level and is asserted by the generator.
  #
  # BUDGET: {spe:,} samples/epoch x {epochs} epochs = {total:,} examples seen
  #         (~6.1 effective passes over 110,087,593 selected training jets).
  #
  # backoffLimit is 1 ON PURPOSE. Raising it only helps if the run can resume
  # from a checkpoint; without verified resume a retry restarts from scratch and
  # burns the budget again. E1 used 12, but E1 staged a much smaller corpus and
  # had a fail-fast GPU smoke test in front of it. Raise this only after
  # checkpoint-resume is demonstrated.
  #
  # Region is pinned because weaver STREAMS from the CephFS PVC at SDSC and is
  # I/O-bound, not GPU-bound: a cross-region pod does not run slowly, it runs at
  # near-zero GPU utilisation. GPU model is pinned separately, for I7b. Both
  # constraints are required and they are not the same constraint.
  name: mtx-{arm_lc}-s{seed}-raunav
  namespace: cms-ml
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: train
        image: {image}
        command: ["/bin/bash", "-c"]
        env:
        # I7b evidence. The node label and the torch-reported device name come
        # from different layers; the manifest records BOTH so a pair whose pod
        # moved after scheduling is detectable after the fact.
        # GPU_PRODUCT is a LITERAL matching the nodeAffinity value below, not a
        # fieldRef: the downward API cannot read node labels, so a fieldRef here
        # would silently record the node NAME under a field the analysis reads
        # as a GPU model. The manifest cross-checks this literal against
        # torch.cuda.get_device_name(0); a disagreement means the pin failed.
        - name: GPU_PRODUCT
          value: "{gpu}"
        - name: NODE_NAME
          valueFrom: {{ fieldRef: {{ fieldPath: spec.nodeName }} }}
        - name: POD_NAME
          valueFrom: {{ fieldRef: {{ fieldPath: metadata.name }} }}
        - name: REGION
          value: "us-west"
        # Pin all three arms to ONE ref. A branch name here means three arms
        # launched at different times can run different code.
        - name: REPO_REF
          value: "{repo_ref}"
        args:
        - |
          set -euo pipefail

          # The image carries no repo. Every other job in this repo clones.
          #
          # --branch takes a TAG here, not the default branch. Cloning a branch
          # tip means three arms launched minutes or days apart each get
          # whatever the tip was AT THAT MOMENT, so the arms could run
          # different code -- precisely the channel I1 and I2 exist to close,
          # and nothing downstream would notice. A tag is an exact pin, and
          # --depth 1 still applies to it, so the clone stays small.
          git clone --depth 1 --branch "${{REPO_REF}}" \
            https://github.com/raunavm/transferlearningsophon.git \
            /workspace/transferlearningsophon
          cd /workspace/transferlearningsophon

          # weaver reads JetClass-II parquet through pyarrow, which the cu121
          # image does not ship. Fail loudly rather than at first fetch.
          pip install --no-cache-dir -q pyarrow || exit 1

          RUN_ID=mtx-{arm_lc}-s{seed}
          OUT=/data/results/mtx/${{RUN_ID}}
          mkdir -p ${{OUT}}

          # Provenance for the two things that can drift between arms launched
          # at different times. pyarrow is deliberately UNPINNED -- guessing a
          # version blind is a worse risk than recording the resolved one --
          # so a mismatch across arms must be detectable after the fact.
          git rev-parse HEAD | tee ${{OUT}}/repo_commit.txt
          python3 -c "import pyarrow; print(pyarrow.__version__)" \
            | tee ${{OUT}}/pyarrow_version.txt

          # ---- split guard -------------------------------------------------
          # All three splits live in ONE directory. A bare glob would train on
          # the held-out test files and bake them into the reweighting
          # histograms, which is unrecoverable: the checkpoints, not just the
          # numbers, would be contaminated.
          #
          # This counts files that ACTUALLY EXIST, not array lengths. The array
          # is a brace expansion, so its length is a compile-time constant that
          # can never disagree with the number asserted next to it -- the old
          # form of this guard verified nothing about the PVC at all. weaver
          # resolves each path with glob.glob (train.py:187, 329) and SILENTLY
          # DROPS anything missing, so a partially-populated or partially-mounted
          # PVC would shrink the training set with no error anywhere.
          TRAIN_FILES=({train_files_plain})
          VAL_FILES=({val_files})
          TEST_FILES=({test_files_plain})
          n_present () {{ local n=0; for f in "$@"; do [ -f "$f" ] && n=$((n+1)); done; echo $n; }}
          N_TRAIN=$(n_present "${{TRAIN_FILES[@]}}")
          N_VAL=$(n_present "${{VAL_FILES[@]}}")
          N_TEST=$(n_present "${{TEST_FILES[@]}}")
          echo "present on PVC: train=${{N_TRAIN}} val=${{N_VAL}} test=${{N_TEST}}"
          [ "${{N_TRAIN}}" -eq {n_train} ] || {{ echo "FATAL: only ${{N_TRAIN}} of {n_train} train files present on the PVC"; exit 1; }}
          [ "${{N_VAL}}"   -eq {n_val} ]   || {{ echo "FATAL: only ${{N_VAL}} of {n_val} val files present on the PVC"; exit 1; }}
          [ "${{N_TEST}}"  -eq {n_test} ]  || {{ echo "FATAL: only ${{N_TEST}} of {n_test} test files present on the PVC"; exit 1; }}

          # ---- reweighting sidecar -----------------------------------------
          # weaver rebuilds the flat-(pT, m_SD) histograms at startup unless a
          # sidecar named <config>.<md5-of-config>.auto.yaml sits next to the
          # config (utils/dataset.py:401-406). --no-remake-weights ALONE does
          # NOT suppress that rebuild: the gate is
          #     if remake_weights or self._data_config.reweight_hists is None
          # (dataset.py:420), and these configs ship reweight_hists empty. Both
          # halves are required.
          #
          # The sidecar must come from job-mtx-makeweight-raunav, which scans
          # train+val (1675 files) per the upstream Sophon recipe. A rebuild
          # here would scan --data-train only (1340 files) -- test-clean either
          # way, but NOT the same histograms, and not the ones
          # docs/GROUND_TRUTH.md describes.
          #
          # The md5 is taken from the config THIS pod cloned, so a config edited
          # after the make_weight pass cannot silently pick up a stale sidecar:
          # the name simply is not found and the run stops here, before the GPU.
          CFG=configs/arms/{arm}.yaml
          MD5=$(md5sum ${{CFG}} | cut -d' ' -f1)
          SIDECAR=configs/arms/{arm}.${{MD5}}.auto.yaml
          SRC=/data/results/mtx/makeweight/{arm}.${{MD5}}.auto.yaml
          [ -f "${{SRC}}" ] || {{ echo "FATAL: no reweighting sidecar at ${{SRC}}. Run job-mtx-makeweight-raunav first. If it HAS run, then configs/arms/{arm}.yaml changed afterwards (its md5 is in the filename) and make_weight must be re-run."; exit 1; }}
          cp -v "${{SRC}}" "${{SIDECAR}}"

          # The reweighting actually used by this run, preserved WITH the run.
          # Without this the realised histograms are unrecoverable afterwards,
          # which is a docs/RECORD.md evidence gap independent of I2.
          cp -v "${{SIDECAR}}" ${{OUT}}/
          sha256sum "${{SIDECAR}}" | tee ${{OUT}}/reweight_sidecar.sha256

          # Manifest FIRST, so a run that dies still has one (docs/RECORD.md).
          python3 scripts/write_run_manifest.py \\
            --run-id ${{RUN_ID}} \\
            --arm {arm} \\
            --num-classes {k} \\
            --seed {seed} \\
            --data-config configs/arms/{arm}.yaml \\
            --samples-per-epoch {spe} \\
            --num-epochs {epochs} \\
            --batch-size {batch} \\
            --out ${{OUT}}/run_manifest.json

          # seed_weaver derives four independent RNG streams and REFUSES to run
          # if it cannot hook weaver's model-construction boundary -- a
          # silently-partial seeding is worse than none, because the run looks
          # seeded and is not.
          PYTHONUNBUFFERED=1 python3 experiments/E1/seed_weaver.py \\
            --seed {seed} \\
            --data-train {train_files} \\
            --data-val {val_files} \\
            --data-test {test_files_plain} \\
            --data-config configs/arms/{arm}.yaml \\
            --no-remake-weights \\
            --network-config experiments/E1/ParT_sophon_arch_10c.py \\
            -o num_classes {k} -o fc_params '[(512,0.1)]' \\
            --use-amp --batch-size {batch} --start-lr {lr} \\
            {data_opts} \\
            --samples-per-epoch {spe} --samples-per-epoch-val {spev} \\
            --num-epochs {epochs} --optimizer ranger \\
            --model-prefix ${{OUT}}/net \\
            --log ${{OUT}}/train.log \\
            --predict-output ${{OUT}}/pred.root \\
            --tensorboard mtx_{arm}_s{seed}

          # pred.root is not optional: docs/GATES.md makes a run without cached
          # ROC arrays a FAILED run even if its AUC is right.
          #
          # --data-test is passed WITHOUT the Res2P:/Res34P:/QCD: prefixes that
          # --data-train carries. On --data-train the prefix is how weaver groups
          # files for reweighting. On --data-test it names an evaluation GROUP,
          # and weaver then renames the output per group -- pred_Res2P.root,
          # pred_Res34P.root, pred_QCD.root -- and never writes pred.root at all
          # (train.py:985-989, group name from train.py:322-333). This guard
          # would then fire after a full GPU-week, marking the run failed and
          # skipping the tensorboard copy below. Unprefixed gives one combined
          # test evaluation over all 335 files, which is what the ROC analysis
          # wants anyway. E1 never hit this: its training job passed no
          # --data-test at all and evaluated in a separate job.
          [ -s ${{OUT}}/pred.root ] || {{ echo "FATAL: no pred.root written"; exit 1; }}
          cp -r ./runs ${{OUT}}/tb 2>/dev/null || true
        resources:
          # 20Gi ephemeral, not 200Gi: nothing is staged locally, the corpus is
          # streamed. A 200Gi request narrows an already narrow node pool for
          # storage that is never used.
          requests: {{ memory: "64Gi", cpu: "8", nvidia.com/gpu: "1", ephemeral-storage: "20Gi" }}
          limits:   {{ memory: "64Gi", cpu: "8", nvidia.com/gpu: "1", ephemeral-storage: "20Gi" }}
        volumeMounts:
        - {{ name: jc2,  mountPath: /jc2, readOnly: true }}
        - {{ name: data, mountPath: /data }}
        - {{ name: dshm, mountPath: /dev/shm }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values: ["us-west"]
              - key: nvidia.com/gpu.product
                operator: In
                values: ["{gpu}"]
      volumes:
      - name: jc2
        persistentVolumeClaim:
          claimName: tn-pvc-base-jetclass2
          readOnly: true
      - name: data
        persistentVolumeClaim:
          claimName: transfer-learning-vol
      # DataLoader workers pass tensors through shared memory; the container
      # default /dev/shm is 64 MB, which stalls or crashes multi-worker loading.
      - name: dshm
        emptyDir: {{ medium: Memory, sizeLimit: "16Gi" }}
"""


def num_classes() -> dict[str, int]:
    rows = list(csv.DictReader(MAPS.open()))
    return {arm: len({int(r[arm]) for r in rows}) for arm in ARMS}


def file_list(split: str, prefixed: bool = True) -> str:
    """Explicit file list for one split, as a shell-expandable brace pattern.

    Brace expansion rather than 1340 literal paths: the same set, but the spec
    stays readable and the index ranges stay visible to a reviewer. The launch
    script counts the expansion and aborts if it is not the expected size, so
    a typo in a range cannot silently shrink or contaminate the training set.
    """
    parts = []
    for fam, (lo, hi) in SPLITS[split].items():
        pat = f"{DATA_DIR}/{fam}_{{{lo:04d}..{hi:04d}}}.parquet"
        parts.append(f"{fam}:{pat}" if prefixed else pat)
    return " ".join(parts)


def split_counts() -> dict[str, int]:
    return {s: sum(hi - lo + 1 for lo, hi in fams.values())
            for s, fams in SPLITS.items()}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check-only", action="store_true")
    ap.add_argument("--pin", default=REPO_REF,
                    help="git ref every arm checks out. A branch name is NOT a "
                         "pin -- pass a tag or full sha for a real launch.")
    args = ap.parse_args()
    if args.pin == REPO_REF:
        print(f"  [WARN] --pin not set: arms will clone the '{REPO_REF}' tip. "
              f"Three arms launched at different times can get different code.")

    failed = 0
    total = SAMPLES_PER_EPOCH * NUM_EPOCHS
    ok = total == TARGET_EXAMPLES
    print(f"  [{'PASS' if ok else 'FAIL'}] budget_arithmetic  "
          f"{SAMPLES_PER_EPOCH:,} x {NUM_EPOCHS} = {total:,} "
          f"(target {TARGET_EXAMPLES:,})")
    failed += not ok

    k_of = num_classes()
    for arm in ARMS:
        cfg = ROOT / "configs" / "arms" / f"{arm}.yaml"
        ok = cfg.exists()
        print(f"  [{'PASS' if ok else 'FAIL'}] arm_config_exists  {arm} -> K={k_of[arm]}")
        failed += not ok

    if failed:
        print(f"\nBUILD FAILED - {failed} check(s), nothing written")
        return 1

    counts = split_counts()
    for s, n in counts.items():
        ok = n == EXPECTED_N[s]
        print(f"  [{'PASS' if ok else 'FAIL'}] split_count_{s:5s}  {n} "
              f"(expected {EXPECTED_N[s]})")
        failed += not ok
    if failed:
        print(f"\nBUILD FAILED - {failed} check(s), nothing written")
        return 1

    specs = {}
    for arm in ARMS:
        for seed in SEEDS:
            specs[f"job-mtx-{arm.lower()}-s{seed}-raunav.yaml"] = TEMPLATE.format(
                arm=arm, arm_lc=arm.lower(), k=k_of[arm], seed=seed,
                spe=SAMPLES_PER_EPOCH, spev=SAMPLES_PER_EPOCH_VAL,
                epochs=NUM_EPOCHS, total=total, batch=BATCH_SIZE,
                lr=START_LR, gpu=GPU_PRODUCT, image=IMAGE,
                data_opts=DATA_OPTS, repo_ref=args.pin,
                train_files=file_list("train"), val_files=file_list("val", False),
                test_files=file_list("test"),
                train_files_plain=file_list("train", False),
                test_files_plain=file_list("test", False),
                n_train=counts["train"], n_val=counts["val"], n_test=counts["test"])

    # I1 at the spec level: strip the four fields that are ALLOWED to differ and
    # assert what remains is byte-identical across arms.
    import re
    def canon(t: str) -> str:
        # Blank out ONLY the four fields a job is allowed to vary in. Anything
        # else that differs is a confound, and this is the check that catches it.
        t = re.sub(r"|".join(ARMS), "ARM", t, flags=re.I)
        # Two spellings reach the same value: weaver takes `-o num_classes K`,
        # the manifest writer takes `--num-classes K`. Both are allowed to vary.
        t = re.sub(r"num[_-]classes \d+", "num_classes K", t)
        t = re.sub(r"K = \d+", "K = K", t)
        t = re.sub(r"-s\d+-raunav", "-sN-raunav", t)
        t = re.sub(r"--seed \d+", "--seed N", t)
        t = re.sub(r"-s\d+\b", "-sN", t)
        return t
    canons = {n: canon(t) for n, t in specs.items()}
    ok = len(set(canons.values())) == 1
    print(f"  [{'PASS' if ok else 'FAIL'}] specs_identical_apart_from_arm_and_K")
    if not ok:
        return 1

    if args.check_only:
        print("\n--check-only: nothing written")
        return 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for name, text in specs.items():
        (OUT_DIR / name).write_text(text)
        print(f"wrote {(OUT_DIR / name).relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
