#!/usr/bin/env python3
"""Emit configs/finetune/*.yaml -- the data configs the fine-tuning legs read.

Each is an existing config with its `weights:` block REMOVED and nothing else
changed, byte for byte:

    JetClassII_L162_noweight.yaml   <- configs/arms/L162.yaml
    JetClassI_sophon_noweight.yaml  <- experiments/E1/data_arm_s.yaml

WHY NO REWEIGHTING WHEN FINE-TUNING
-----------------------------------
The flat (pT, m_SD) reweighting is a pretraining device: weaver builds its
histograms from the training files, and on a 10,000-jet subset those
histograms are noise, so the realised weights would differ arbitrarily between
N=1e4 and N=1e6 -- a second variable riding on the one the leg varies. The
2026 fine-tuning protocols the paper is measured against (2606.14870 §III.B,
2606.19781 §3.3, 2607.23377 §VII.D) all fine-tune on the downstream sample at
its natural composition. So do these legs. The scratch reference at N_max for
JetClass-I (E1 arm S) WAS trained with reweighting; the paper says so where it
is used as a denominator.

These live under configs/finetune/, NOT configs/arms/: tests/test_arm_configs.py
asserts every file in configs/arms/ is byte-identical to the base outside its
labels block, and a config with no weights: block is not an arm.

Run:  python3 scripts/build_finetune_configs.py [--check-only]
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "configs" / "finetune"
SOURCES = {
    "JetClassII_L162_noweight.yaml": ROOT / "configs" / "arms" / "L162.yaml",
    "JetClassI_sophon_noweight.yaml": ROOT / "experiments" / "E1" / "data_arm_s.yaml",
}


def strip_weights(text: str, src: pathlib.Path, name: str) -> str:
    m = re.search(r"^weights:", text, re.M)
    if not m:
        sys.exit(f"FATAL: {src} has no weights: block")
    tail = text[m.end():]
    if re.search(r"^[a-z_]+:", tail, re.M):
        sys.exit(f"FATAL: {src}: weights: is not the last top-level section")
    header = (
        f"# configs/finetune/{name}\n"
        f"# GENERATED by scripts/build_finetune_configs.py -- do not hand-edit.\n"
        f"#\n"
        f"# {src.relative_to(ROOT)} with its `weights:` block removed and NOTHING\n"
        f"# else changed. Fine-tuning subsets are used at their natural composition;\n"
        f"# see the generator's docstring. Not an arm: lives outside configs/arms/.\n"
        f"#\n"
    )
    body = text[:m.start()].rstrip("\n") + "\n"
    return header, body


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check-only", action="store_true")
    args = ap.parse_args()
    built = {}
    for name, src in SOURCES.items():
        if not src.exists():
            sys.exit(f"FATAL: {src} not found")
        header, body = strip_weights(src.read_text(), src, name)
        # the part that survives must be the source's own bytes
        assert src.read_text().startswith(body.rstrip("\n")), name
        assert not re.search(r"^weights:", body, re.M), name
        built[name] = header + body
        print(f"  [PASS] {name}: source bytes preserved, weights: removed")
    if args.check_only:
        return 0
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for name, text in built.items():
        (OUT_DIR / name).write_text(text)
        print(f"wrote configs/finetune/{name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
