#!/usr/bin/env python3
"""Emit review/groupings/SUMMARY.md -- group sizes and effective stream shares.

Kept OUT of the CSVs so the three-column contract (sophon_signal_name,
group_id, group_name) stays fixed. Every number here is derived from
hierarchy/01_class_master.csv; nothing is transcribed.

Share provenance, per group:
  EXACT    the group is a union of WHOLE reweighting groups, so its share is
           exact rational algebra on class_weights (sum 1.73175).
  NOMINAL  the group cuts inside a reweighting group, so the share assumes
           uniform occupancy WITHIN that reweighting group. That assumption is
           NOT verified (hierarchy/00_README.md) and is measured at G-0.
           A nominal number must never be written into a measured column.

Run:  python3 scripts/build_review_summary.py
"""
from __future__ import annotations

import csv
import pathlib
from collections import defaultdict
from fractions import Fraction

ROOT = pathlib.Path(__file__).resolve().parent.parent
MASTER = ROOT / "hierarchy" / "01_class_master.csv"
SRC = ROOT / "review" / "groupings" / "JetClass2_all_8_grouping_CSVs"
OUT = ROOT / "review" / "groupings" / "SUMMARY.md"

CLASS_WEIGHTS_SUM = Fraction("1.73175")
RUNGS = ["L188", "L162", "R63_Q1", "R42_Q1", "R29_Q1", "R16_Q1", "R3_Q1", "R1_Q1"]
# LADDER omitted R63_Q1 until 2026-08-27, so the summary printed the one rung
# that retains heavy-flavour MULTIPLICITY as though it were off-ladder. D3 as
# amended has eight rungs; this is the only place the four-vs-eight split was
# executable rather than prose.
#
# The tag stays R3_Q1, NOT R3_VIS: load_rung() reads SRC / f"{tag}.csv" and the
# on-disk reference file is R3_Q1.csv. Renaming the tag here breaks the read.
# That rename is gated on regenerating the reference CSV.
LADDER = ["L188", "L162", "R63_Q1", "R42_Q1", "R29_Q1", "R16_Q1", "R3_Q1", "R1_Q1"]
# rungs whose per-group listing is too long to be useful in a review document
LIST_CAP = 70


def load_master() -> dict[str, dict]:
    return {r["class_name"]: r for r in csv.DictReader(MASTER.open())}


def load_rung(tag: str) -> dict[str, tuple[int, str]]:
    path = SRC / f"{tag}.csv"
    return {r["Actual Sophon class name"]: (int(r["Group number"]), r["Group class name"])
            for r in csv.DictReader(path.open())}


def group_stats(master, rung_map):
    """(gid, name) -> (members, share, exact)."""
    rw_members = defaultdict(set)
    for cn, r in master.items():
        rw_members[r["reweight_group_name"]].add(cn)

    groups = defaultdict(set)
    for cn, (gid, name) in rung_map.items():
        groups[(gid, name)].add(cn)

    out = {}
    for key, members in groups.items():
        rws = {master[c]["reweight_group_name"] for c in members}
        exact = all(rw_members[rw] <= members for rw in rws)
        if exact:
            share = sum(Fraction(str(master[next(iter(rw_members[rw]))]["reweight_group_weight"]))
                        for rw in rws) / CLASS_WEIGHTS_SUM
        else:
            share = sum(Fraction(str(master[c]["class_weight_share_frac"])) for c in members)
        out[key] = (members, float(share), exact)
    return out


def main() -> None:
    master = load_master()
    stats = {tag: group_stats(master, load_rung(tag)) for tag in RUNGS}

    L = []
    a = L.append
    a("# Grouping summary — sizes and effective stream shares")
    a("")
    a("Generated by `scripts/build_review_summary.py` from")
    a("`hierarchy/01_class_master.csv`. Do not hand-edit — rerun the script.")
    a("")
    a("These numbers are deliberately **not** in the CSVs, so the three-column")
    a("contract there stays fixed.")
    a("")
    a("## Share provenance — read this before quoting any number")
    a("")
    a("| flag | meaning |")
    a("|---|---|")
    a("| `EXACT` | the group is a union of **whole** reweighting groups, so its share is "
      "exact rational algebra on `class_weights` (sum 1.73175) |")
    a("| `NOMINAL` | the group **cuts inside** a reweighting group, so the share assumes "
      "uniform occupancy *within* that reweighting group |")
    a("")
    a("**The uniformity assumption behind `NOMINAL` is not verified.** It is measured at")
    a("G-0. A nominal number must never be written into a measured column — that is how")
    a("this repository previously quoted upper bounds as fact.")
    a("")
    a("## Rung overview")
    a("")
    a("| rung | groups | share method | min share | max share | imbalance | singletons |")
    a("|---|---:|---|---:|---:|---:|---:|")
    for tag in RUNGS:
        s = stats[tag]
        shares = [v[1] for v in s.values()]
        sizes = [len(v[0]) for v in s.values()]
        n_cut = sum(1 for v in s.values() if not v[2])
        method = "exact" if n_cut == 0 else f"nominal ({n_cut}/{len(s)} cut)"
        mark = "" if tag in LADDER else " *"
        a(f"| `{tag}`{mark} | {len(s)} | {method} | {min(shares)*100:.4f}% | "
          f"{max(shares)*100:.4f}% | {max(shares)/min(shares):.1f}:1 | "
          f"{sum(1 for n in sizes if n == 1)} |")
    a("")
    a("`*` not on the seven-rung ladder — `R63_Q1` is held pending the multiplicity")
    a("pre-test; `R3_Q1` is the generated-object variant of the prong rung (see")
    a("`JUDGMENT_CALLS.md`, call J6).")
    a("")
    a("Imbalance is **per group at that rung**. It is not the per-class (222.2:1) or")
    a("per-reweighting-category (888.9:1) figure — always say which level you mean.")
    a("")

    for tag in RUNGS:
        s = stats[tag]
        a(f"## `{tag}` — {len(s)} groups")
        a("")
        if len(s) > LIST_CAP:
            shares = sorted(((v[1], k, len(v[0])) for k, v in s.items()))
            a(f"Too many groups to list. Smallest and largest five by stream share:")
            a("")
            a("| group_id | group_name | natives | share |")
            a("|---:|---|---:|---:|")
            for sh, k, n in shares[:5]:
                a(f"| `{k[0]:03d}` | `{k[1]}` | {n} | {sh*100:.5f}% |")
            a("| … | … | … | … |")
            for sh, k, n in shares[-5:]:
                a(f"| `{k[0]:03d}` | `{k[1]}` | {n} | {sh*100:.5f}% |")
            a("")
            continue
        a("| group_id | group_name | natives | share | provenance |")
        a("|---:|---|---:|---:|---|")
        for k in sorted(s):
            members, share, exact = s[k]
            a(f"| `{k[0]:03d}` | `{k[1]}` | {len(members)} | {share*100:.5f}% | "
              f"{'EXACT' if exact else 'NOMINAL'} |")
        a("")

    OUT.write_text("\n".join(L) + "\n")
    print(f"wrote {OUT}  ({len(L)} lines)")


if __name__ == "__main__":
    main()
