#!/usr/bin/env python3
"""Emit the AspenOpenJets INFERENCE config and its JetClass-II closure reference.

Both files are assembled from scripts/build_downstream_configs.py's own pieces --
FEATURES, NEW_VARIABLES_COMMON, _inputs_block() and control() -- called with
`missing = []`, i.e. the FILLS mechanism with NOTHING filled: AspenOpenJets
carries all 17 per-particle features. They are not a FILLS *entry*, for three
reasons that are about that module and not about this dataset:

  1. `downstream()` never defines part_d0 / part_dz. Both existing FILLS entries
     lack displacement, so NEW_VARIABLES_COMMON omits the arms'
     `part_d0: np.tanh(part_d0val)`; with nothing filled the emitted config
     would read a raw `part_d0` branch that does not exist. The two tanh lines
     are added here, copied from configs/data/JetClassII_base.yaml:24-25.
  2. `downstream()` hard-codes `observers: [jet_pt, jet_energy]`; this job needs
     m_SD, eta, the shipped ParticleNet scores and run/lumi/event.
  3. A FILLS entry makes main() emit two zero-fill CONTROLS and a header that
     names them. With nothing filled those controls are the unmasked configs
     under a misleading name.

  configs/finetune/AspenOpenJets.yaml
      inference only: a dummy two-indicator label (weaver's `simple` type
      argmaxes over indicators; one indicator would be a width-1 argmax), NO
      `weights:` block, the staging selection repeated so a differently-staged
      file cannot slip through.
  configs/finetune/JetClassII_base_selAspenOpenJets.yaml
      configs/data/JetClassII_base.yaml through control() with nothing masked --
      weights dropped, inputs and native labels untouched -- and the selection
      line replaced by the AspenOpenJets one. experiments/AOJ/closure.py reads
      JetClass-II QCD through it, so the reference population has the same
      kinematics as the data it is compared with.

Neither file touches a `weights:` block: one has none by construction, the other
has it REMOVED by control(), never edited.

Run:  python3 scripts/build_aoj_config.py [--check-only]
"""
from __future__ import annotations

import argparse
import importlib.util
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "configs" / "finetune"
BASE = ROOT / "configs" / "data" / "JetClassII_base.yaml"
BASE_SELECTION = "   (jet_pt > 200) & (jet_pt < 2500) & (jet_sdmass > 20) & (jet_sdmass < 500)\n"


def _load(name):
    spec = importlib.util.spec_from_file_location(name, ROOT / "scripts" / f"{name}.py")
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)
    return m


bdc = _load("build_downstream_configs")
SEL = _load("stage_aoj").SELECTION


def selection(pt: str, eta: str) -> str:
    """The staging selection as a weaver expression, from stage_aoj.SELECTION."""
    s = SEL
    return (f"({pt} > {s['pt_min']:g}) & ({pt} < {s['pt_max']:g}) & "
            f"(np.abs({eta}) < {s['abs_eta_max']:g}) & "
            f"(jet_sdmass > {s['sdmass_min']:g}) & (jet_sdmass < {s['sdmass_max']:g})")


OBSERVERS = ["jet_pt", "jet_eta", "jet_sdmass", "aoj_jet_pt", "aoj_jet_eta",
             "aoj_pn_WvsQCD", "aoj_pn_TvsQCD", "aoj_pn_HbbvsQCD", "run", "lumi", "event"]

HEADER = """# configs/finetune/AspenOpenJets.yaml
# GENERATED by scripts/build_aoj_config.py -- do not hand-edit.
#
# AspenOpenJets, CMS 2016 JetHT Open Data (arXiv:2412.10504, DOI
# 10.25592/uhhfdm.16505), staged by scripts/stage_aoj.py. INFERENCE ONLY.
#
# All 17 per-particle features are present, so NOTHING is zero-filled: the
# inputs block is scripts/build_downstream_configs.py's with `missing = []`,
# i.e. the arms' slots and standardization verbatim.
#
# jet_pt / jet_energy are REBUILT from the PUPPI-weighted constituents (what the
# constituents are normalised by); aoj_jet_pt is the JEC-corrected CMS value and
# is what the selection cuts on. The label is a dummy -- this is real data.
#
# No `weights:` block.
"""

REF_HEADER = """# configs/finetune/JetClassII_base_selAspenOpenJets.yaml
# GENERATED by scripts/build_aoj_config.py -- do not hand-edit.
#
# CLOSURE REFERENCE for configs/finetune/AspenOpenJets.yaml. This is
# configs/data/JetClassII_base.yaml with the `weights:` block dropped (a read
# pass does not reweight), NO input masked, the native label block untouched,
# and the selection replaced by the AspenOpenJets staging selection so
# experiments/AOJ/closure.py compares like kinematics with like.
"""


def aoj_config() -> str:
    dummy = ("\n   ## displacement, as configs/data/JetClassII_base.yaml:24-25\n"
             "   part_d0: np.tanh(part_d0val)\n"
             "   part_dz: np.tanh(part_dzval)\n"
             "\n   ## dummy class indicators (weaver argmaxes over these); real data has no label\n"
             "   label_data: label == 0\n"
             "   label_unused: label == 1\n")
    return (HEADER + "\nselection:\n   " + selection("aoj_jet_pt", "aoj_jet_eta") + "\n"
            + bdc.NEW_VARIABLES_COMMON.format(zeros=bdc._zero_defs([])) + dummy
            + "\npreprocess:\n  method: manual\n  data_fraction: 0.5\n"
            + bdc._inputs_block([])
            + "\nlabels:\n   type: simple\n   value: [label_data, label_unused]\n"
            + "\nobservers:\n" + "".join(f"   - {o}\n" for o in OBSERVERS))


def reference_config() -> str:
    body = bdc.control("AspenOpenJets", dict(missing=[]), BASE.read_text(), REF_HEADER,
                       source_path=BASE)
    if body.count(BASE_SELECTION) != 1:
        raise SystemExit(f"build_aoj_config: the selection line of {BASE} has changed")
    return body.replace(BASE_SELECTION, "   " + selection("jet_pt", "jet_eta") + "\n")


TARGETS = {"AspenOpenJets.yaml": aoj_config,
           "JetClassII_base_selAspenOpenJets.yaml": reference_config}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check-only", action="store_true")
    a = ap.parse_args()
    stale = []
    for name, build in TARGETS.items():
        path, text = OUT_DIR / name, build()
        if a.check_only:
            if not path.exists() or path.read_text() != text:
                stale.append(name)
        else:
            path.write_text(text)
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        print("STALE (re-run scripts/build_aoj_config.py): " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
